# I would like to plot these variables:
# KEY: TH1D      nel_cut3;1      nel
# KEY: TH1D      elEta_cut3;1    elEta
# KEY: TH1D      elPt_cut3;1     elPt
# KEY: TH1D      uT_cut3;1       uT
# KEY: TH1D      met_cut3;1      met
# KEY: TH1D      mT_cut3;1       mT
# KEY: TH1D      ptcone20topT_cut3;1     ptcone20topT
# KEY: TH1D      uParLepton_cut3;1       uParLepton
# KEY: TH2D      uParLepton_vs_ptcone20_cut3;1   uParLepton_vs_ptcone20
# KEY: TH2D      WpT_Reco_vs_ptcone20topT_cut3;1 WpT_Reco_vs_ptcone20topT
# KEY: TH2D      elPhi_vs_ptcone20topT_cut3;1    elPhi_vs_ptcone20topT
# KEY: TH2D      elEta_vs_ptcone20topT_cut3;1    elEta_vs_ptcone20topT
# KEY: TH2D      elEtaSF_vs_ptcone20topT_cut3;1  elEtaSF_vs_ptcone20topT
# KEY: TH2D      elPt_vs_ptcone20topT_cut3;1     elPt_vs_ptcone20topT
# KEY: TH2D      uT_vs_ptcone20topT_cut3;1       uT_vs_ptcone20topT
# KEY: TH2D      met_vs_ptcone20topT_cut3;1      met_vs_ptcone20topT
# KEY: TH2D      mT_vs_ptcone20topT_cut3;1       mT_vs_ptcone20topT
# KEY: TH2D      SET_vs_ptcone20topT_cut3;1      SET_vs_ptcone20topT
# KEY: TH2D      SETUE_vs_ptcone20topT_cut3;1    SETUE_vs_ptcone20topT
# KEY: TH2D      recoil_PAR_lep_vs_ptcone20topT_cut3;1   recoil_PAR_lep_vs_ptcone20topT
# KEY: TH2D      recoil_PERP_lep_vs_ptcone20topT_cut3;1  recoil_PERP_lep_vs_ptcone20topT
# KEY: TH2D      mT_ut1_vs_ptcone20topT_cut3;1   mT_ut1_vs_ptcone20topT
# KEY: TH2D      mT_ut2_vs_ptcone20topT_cut3;1   mT_ut2_vs_ptcone20topT
# KEY: TH2D      mT_ut3_vs_ptcone20topT_cut3;1   mT_ut3_vs_ptcone20topT
# KEY: TH2D      mT_ut4_vs_ptcone20topT_cut3;1   mT_ut4_vs_ptcone20topT
# KEY: TH2D      mT_ut5_vs_ptcone20topT_cut3;1   mT_ut5_vs_ptcone20topT
# KEY: TH2D      elPt_ut1_vs_ptcone20topT_cut3;1 elPt_ut1_vs_ptcone20topT
# KEY: TH2D      elPt_ut2_vs_ptcone20topT_cut3;1 elPt_ut2_vs_ptcone20topT
# KEY: TH2D      elPt_ut3_vs_ptcone20topT_cut3;1 elPt_ut3_vs_ptcone20topT
# KEY: TH2D      elPt_ut4_vs_ptcone20topT_cut3;1 elPt_ut4_vs_ptcone20topT
# KEY: TH2D      elPt_ut5_vs_ptcone20topT_cut3;1 elPt_ut5_vs_ptcone20topT
# KEY: TH2D      met_ut1_vs_ptcone20topT_cut3;1  met_ut1_vs_ptcone20topT
# KEY: TH2D      met_ut2_vs_ptcone20topT_cut3;1  met_ut2_vs_ptcone20topT
# KEY: TH2D      met_ut3_vs_ptcone20topT_cut3;1  met_ut3_vs_ptcone20topT
# KEY: TH2D      met_ut4_vs_ptcone20topT_cut3;1  met_ut4_vs_ptcone20topT
# KEY: TH2D      met_ut5_vs_ptcone20topT_cut3;1  met_ut5_vs_ptcone20topT

# Job block defines the output directory and the input file and common plot styles
Job:
  job_name: "Wenu_13TeV_Sherpa_0_5"  # this is a folder name where the plots will be saved
  output_directory: "fal_out_Wlnu/Wenu_plots/"  # this is the output directory where the plots will be saved
  #file_path:  &file_path "output_1.root"  # this is the file where the histograms are stored
  file_paths: # this is a list of files or wildcard patterns where the histograms are stored
    - "fal_out_Wlnu/Wenu/output_0.root"
    - "fal_out_Wlnu/Wenu/output_1.root"
    - "fal_out_Wlnu/Wenu/output_2.root"
    - "fal_out_Wlnu/Wenu/output_3.root"
    - "fal_out_Wlnu/Wenu/output_4.root"
    - "fal_out_Wlnu/Wenu/output_5.root"
  # add text block in the plot for example : sqrt(s) = 13 TeV
  atlas_label: "Internal" #0.22, 0.9
  plot_label:
    - text: "W^{+} #rightarrow e^{+} #nu"
      x: 0.22
      y: 0.86
    - text: ", #sqrt{s} = 13 TeV"
      x: 0.45
      y: 0.86

  # Define common styles
  CommonStyles: &CommonStyles
    markerstyle: 0
    linestyle: 1
    linewidth: 2

# Sample block holds information of individual histograms
Sample:
  - name: "uT_cut3"  # name of the sample
    variable: "WplusenuSelection_Tight/uT_cut3"  # this is the name of the histogram in the ROOT file
  - name: "nel_cut3"
    variable: "WplusenuSelection_Tight/nel_cut3"
  - name: "elEta_cut3"
    variable: "WplusenuSelection_Tight/elEta_cut3"
  - name: "elPt_cut3"
    variable: "WplusenuSelection_Tight/elPt_cut3"
  - name: "met_cut3"
    variable: "WplusenuSelection_Tight/met_cut3"
  - name: "mT_cut3"
    variable: "WplusenuSelection_Tight/mT_cut3"
  - name: "ptcone20topT_cut3"
    variable: "WplusenuSelection_Tight/ptcone20topT_cut3"
  - name: "uParLepton_cut3"
    variable: "WplusenuSelection_Tight/uParLepton_cut3"
  - name: "uParLepton_vs_ptcone20_cut3"
    variable: "WplusenuSelection_Tight/uParLepton_vs_ptcone20_cut3"
  - name: "WpT_Reco_vs_ptcone20topT_cut3"
    variable: "WplusenuSelection_Tight/WpT_Reco_vs_ptcone20topT_cut3"
  - name: "elPhi_vs_ptcone20topT_cut3"
    variable: "WplusenuSelection_Tight/elPhi_vs_ptcone20topT_cut3"
  - name: "elEta_vs_ptcone20topT_cut3"
    variable: "WplusenuSelection_Tight/elEta_vs_ptcone20topT_cut3"
  - name: "elEtaSF_vs_ptcone20topT_cut3"
    variable: "WplusenuSelection_Tight/elEtaSF_vs_ptcone20topT_cut3"
  - name: "elPt_vs_ptcone20topT_cut3"
    variable: "WplusenuSelection_Tight/elPt_vs_ptcone20topT_cut3"
  - name: "uT_vs_ptcone20topT_cut3"
    variable: "WplusenuSelection_Tight/uT_vs_ptcone20topT_cut3"
  - name: "met_vs_ptcone20topT_cut3"
    variable: "WplusenuSelection_Tight/met_vs_ptcone20topT_cut3"
  - name: "mT_vs_ptcone20topT_cut3"
    variable: "WplusenuSelection_Tight/mT_vs_ptcone20topT_cut3"
  - name: "SET_vs_ptcone20topT_cut3"
    variable: "WplusenuSelection_Tight/SET_vs_ptcone20topT_cut3"
  - name: "SETUE_vs_ptcone20topT_cut3"
    variable: "WplusenuSelection_Tight/SETUE_vs_ptcone20topT_cut3"
  - name: "recoil_PAR_lep_vs_ptcone20topT_cut3"
    variable: "WplusenuSelection_Tight/recoil_PAR_lep_vs_ptcone20topT_cut3"
  - name: "recoil_PERP_lep_vs_ptcone20topT_cut3"
    variable: "WplusenuSelection_Tight/recoil_PERP_lep_vs_ptcone20topT_cut3"
  - name: "mT_ut1_vs_ptcone20topT_cut3"
    variable: "WplusenuSelection_Tight/mT_ut1_vs_ptcone20topT_cut3"
  - name: "mT_ut2_vs_ptcone20topT_cut3"
    variable: "WplusenuSelection_Tight/mT_ut2_vs_ptcone20topT_cut3"
  - name: "mT_ut3_vs_ptcone20topT_cut3"
    variable: "WplusenuSelection_Tight/mT_ut3_vs_ptcone20topT_cut3"
  - name: "mT_ut4_vs_ptcone20topT_cut3"
    variable: "WplusenuSelection_Tight/mT_ut4_vs_ptcone20topT_cut3"
  - name: "mT_ut5_vs_ptcone20topT_cut3"
    variable: "WplusenuSelection_Tight/mT_ut5_vs_ptcone20topT_cut3"
  - name: "elPt_ut1_vs_ptcone20topT_cut3"
    variable: "WplusenuSelection_Tight/elPt_ut1_vs_ptcone20topT_cut3"
  - name: "elPt_ut2_vs_ptcone20topT_cut3"
    variable: "WplusenuSelection_Tight/elPt_ut2_vs_ptcone20topT_cut3"
  - name: "elPt_ut3_vs_ptcone20topT_cut3"
    variable: "WplusenuSelection_Tight/elPt_ut3_vs_ptcone20topT_cut3"
  - name: "elPt_ut4_vs_ptcone20topT_cut3"
    variable: "WplusenuSelection_Tight/elPt_ut4_vs_ptcone20topT_cut3"
  - name: "elPt_ut5_vs_ptcone20topT_cut3"
    variable: "WplusenuSelection_Tight/elPt_ut5_vs_ptcone20topT_cut3"
  - name: "met_ut1_vs_ptcone20topT_cut3"
    variable: "WplusenuSelection_Tight/met_ut1_vs_ptcone20topT_cut3"
  - name: "met_ut2_vs_ptcone20topT_cut3"
    variable: "WplusenuSelection_Tight/met_ut2_vs_ptcone20topT_cut3"
  - name: "met_ut3_vs_ptcone20topT_cut3"
    variable: "WplusenuSelection_Tight/met_ut3_vs_ptcone20topT_cut3"
  - name: "met_ut4_vs_ptcone20topT_cut3"
    variable: "WplusenuSelection_Tight/met_ut4_vs_ptcone20topT_cut3"
  - name: "met_ut5_vs_ptcone20topT_cut3"
    variable: "WplusenuSelection_Tight/met_ut5_vs_ptcone20topT_cut3"


# Every block in the Plot block holds a plot
Plot:
  - name: "uT"  # this is the name of the plot
    samples:
      - name: "uT_cut3"
        linecolor: 1
        <<: *CommonStyles
    type: "overlay"  # different typs of plots: overlay, simple_th2, stack ...
    y_label: "Events"  # y-axis label
    x_range: [0, 150]  # x-axis range

  - name: "nel"
    samples:
      - name: "nel_cut3"
        linecolor: 1
        <<: *CommonStyles
    type: "overlay"
    y_label: "Events"
    x_range: [0, 5]

  - name: "elEta"
    samples:
      - name: "elEta_cut3"
        linecolor: 1
        <<: *CommonStyles
    type: "overlay"
    y_label: "Events"
    x_range: [-3, 3]

  - name: "elPt"
    samples:
      - name: "elPt_cut3"
        linecolor: 1
        <<: *CommonStyles
    type: "overlay"
    y_label: "Events"
    x_range: [0, 150]

  - name: "met"
    samples:
      - name: "met_cut3"
        linecolor: 1
        <<: *CommonStyles
    type: "overlay"
    y_label: "Events"
    x_range: [0, 150]

  - name: "mT"
    samples:
      - name: "mT_cut3"
        linecolor: 1
        <<: *CommonStyles
    type: "overlay"
    y_label: "Events"
    x_range: [0, 150]

  - name: "ptcone20topT"
    samples:
      - name: "ptcone20topT_cut3"
        linecolor: 1
        <<: *CommonStyles
    type: "overlay"

  - name: "uParLepton"
    samples:
      - name: "uParLepton_cut3"
        linecolor: 1
        <<: *CommonStyles
    type: "overlay"
    y_label: "Events"

  - name: "uParLepton_vs_ptcone20"
    samples:
      - name: "uParLepton_vs_ptcone20_cut3"
        <<: *CommonStyles
    type: "simple_th2"

  - name: "WpT_Reco_vs_ptcone20topT"
    samples:
      - name: "WpT_Reco_vs_ptcone20topT_cut3"
        <<: *CommonStyles
    type: "simple_th2"

  - name: "elPhi_vs_ptcone20topT"
    samples:
      - name: "elPhi_vs_ptcone20topT_cut3"
        <<: *CommonStyles
    type: "simple_th2"

  - name: "elEta_vs_ptcone20topT"
    samples:
      - name: "elEta_vs_ptcone20topT_cut3"
        <<: *CommonStyles
    type: "simple_th2"

  - name: "elEtaSF_vs_ptcone20topT"
    samples:
      - name: "elEtaSF_vs_ptcone20topT_cut3"
        <<: *CommonStyles
    type: "simple_th2"

  - name: "elPt_vs_ptcone20topT"
    samples:
      - name: "elPt_vs_ptcone20topT_cut3"
        <<: *CommonStyles
    type: "simple_th2"

  - name: "uT_vs_ptcone20topT"
    samples:
      - name: "uT_vs_ptcone20topT_cut3"
        <<: *CommonStyles
    type: "simple_th2"

  - name: "met_vs_ptcone20topT"
    samples:
      - name: "met_vs_ptcone20topT_cut3"
        <<: *CommonStyles
    type: "simple_th2"

  - name: "mT_vs_ptcone20topT"
    samples:
      - name: "mT_vs_ptcone20topT_cut3"
        <<: *CommonStyles
    type: "simple_th2"

  - name: "SET_vs_ptcone20topT"
    samples:
      - name: "SET_vs_ptcone20topT_cut3"
        <<: *CommonStyles
    type: "simple_th2"

  - name: "SETUE_vs_ptcone20topT"
    samples:
      - name: "SETUE_vs_ptcone20topT_cut3"
        <<: *CommonStyles
    type: "simple_th2"

  - name: "recoil_PAR_lep_vs_ptcone20topT"
    samples:
      - name: "recoil_PAR_lep_vs_ptcone20topT_cut3"
        <<: *CommonStyles
    type: "simple_th2"
    y_label: "p_{T}^{cone20}/p_{T}"

  - name: "recoil_PERP_lep_vs_ptcone20topT"
    samples:
      - name: "recoil_PERP_lep_vs_ptcone20topT_cut3"
        <<: *CommonStyles
    type: "simple_th2"
    y_label: "p_{T}^{cone20}/p_{T}"

  - name: "mT_ut1_vs_ptcone20topT"
    samples:
      - name: "mT_ut1_vs_ptcone20topT_cut3"
        <<: *CommonStyles
    type: "simple_th2"

  - name: "mT_ut2_vs_ptcone20topT"
    samples:
      - name: "mT_ut2_vs_ptcone20topT_cut3"
        <<: *CommonStyles
    type: "simple_th2"

  - name: "mT_ut3_vs_ptcone20topT"
    samples:
      - name: "mT_ut3_vs_ptcone20topT_cut3"
        <<: *CommonStyles
    type: "simple_th2"

  - name: "mT_ut4_vs_ptcone20topT"
    samples:
      - name: "mT_ut4_vs_ptcone20topT_cut3"
        <<: *CommonStyles
    type: "simple_th2"

  - name: "mT_ut5_vs_ptcone20topT"
    samples:
      - name: "mT_ut5_vs_ptcone20topT_cut3"
        <<: *CommonStyles
    type: "simple_th2"

  - name: "elPt_ut1_vs_ptcone20topT"
    samples:
      - name: "elPt_ut1_vs_ptcone20topT_cut3"
        <<: *CommonStyles
    type: "simple_th2"

  - name: "elPt_ut2_vs_ptcone20topT"
    samples:
      - name: "elPt_ut2_vs_ptcone20topT_cut3"
        <<: *CommonStyles
    type: "simple_th2"

  - name: "elPt_ut3_vs_ptcone20topT"
    samples:
      - name: "elPt_ut3_vs_ptcone20topT_cut3"
        <<: *CommonStyles
    type: "simple_th2"

  - name: "elPt_ut4_vs_ptcone20topT"
    samples:
      - name: "elPt_ut4_vs_ptcone20topT_cut3"
        <<: *CommonStyles
    type: "simple_th2"

  - name: "elPt_ut5_vs_ptcone20topT"
    samples:
      - name: "elPt_ut5_vs_ptcone20topT_cut3"
        <<: *CommonStyles
    type: "simple_th2"

  - name: "met_ut1_vs_ptcone20topT"
    samples:
      - name: "met_ut1_vs_ptcone20topT_cut3"
        <<: *CommonStyles
    type: "simple_th2"

  - name: "met_ut2_vs_ptcone20topT"
    samples:
      - name: "met_ut2_vs_ptcone20topT_cut3"
        <<: *CommonStyles
    type: "simple_th2"

  - name: "met_ut3_vs_ptcone20topT"
    samples:
      - name: "met_ut3_vs_ptcone20topT_cut3"
        <<: *CommonStyles
    type: "simple_th2"

  - name: "met_ut4_vs_ptcone20topT"
    samples:
      - name: "met_ut4_vs_ptcone20topT_cut3"
        <<: *CommonStyles
    type: "simple_th2"

  - name: "met_ut5_vs_ptcone20topT"
    samples:
      - name: "met_ut5_vs_ptcone20topT_cut3"
        <<: *CommonStyles
    type: "simple_th2"
