# This is a configuration file used for plotting
# simple histograms from the cluster truth study
Job:
  job_name: "ClusterStudyPlots"  # this is a folder name where the plots will be saved
  output_directory: "/home/bmondal/Storage/HEP/Work/Project-W-Z/Plotter/plotter/run/Topo-cluster-truth-study/Plots/"
  #file_path:  &file_path "output_1.root"  # this is the file where the histograms are stored
  file_paths: # this is a list of files or wildcard patterns where the histograms are stored
    - "/home/bmondal/Storage/HEP/Work/Project-W-Z/Plotter/plotter/run/Topo-cluster-truth-study/Root-files/ClusterEnergies.root"
  atlas_label: "Internal" #0.22, 0.9

  # Define common styles
  # its applied automatically to all histograms
  CommonStyles: &CommonStyles
    markerstyle: 0
    linestyle: 1
    linewidth: 2

# Sample block holds information of individual histograms
Sample:
  - name: "TrueVsCalibrated"
    variable: "TrueVsCalibrated"
  - name: "TrueVsUncalibrated"
    variable: "TrueVsUncalibrated"
  - name: "uTFromClusters"
    variable: "uTFromClusters"
  - name: "uTFromPFOs"
    variable: "uTFromPFOs"
  - name: "CellSignificance"
    variable: "CellSignificance"
  - name: "EnergyInEta_0.0_1.0"
    variable: "EnergyInEta_0.0_1.0"
    normalize: true
  - name: "EnergyInEta_1.0_2.0"
    variable: "EnergyInEta_1.0_2.0"
    normalize: true
  - name: "EnergyInEta_2.0_3.0"
    variable: "EnergyInEta_2.0_3.0"
    normalize: true
  - name: "EnergyInEta_3.0_4.0"
    variable: "EnergyInEta_3.0_4.0"
    normalize: true
  - name: "EnergyInEta_4.0_5.0"
    variable: "EnergyInEta_4.0_5.0"
    normalize: true
  - name: "EEmOverETrue"
    variable: "EEmOverETrue"
  - name: "ELcwOverETrue"
    variable: "ELcwOverETrue"



Plot:
  - name: "TrueVsCalibrated"
    samples:
      - name: "TrueVsCalibrated"
    type: "simple_th2"
  - name: "TrueVsUncalibrated"
    samples:
      - name: "TrueVsUncalibrated"
    type: "simple_th2"
  - name: "uTFromPFOsAndCluster"
    samples: [{name: "uTFromClusters", linecolor: 1},{name: "uTFromPFOs", linecolor: 2}]
    type: "overlay"
  - name: "CellSignificance"
    samples:
      - name: "CellSignificance"
        linecolor: 1
    type: "simple_th1"
  - name: "comp_cell_significance"
    samples: [{name: "EnergyInEta_0.0_1.0", linecolor: 1}, {name: "EnergyInEta_1.0_2.0", linecolor: 2}, {name: "EnergyInEta_2.0_3.0", linecolor: 3}, {name: "EnergyInEta_3.0_4.0", linecolor: 4}, {name: "EnergyInEta_4.0_5.0", linecolor: 6}]
    type: "simple_th1"
    #setlogy: true
    #setlogx: true
    xaxis_title: "Cell significance"
  - name: "EOverETrue"
    samples:
      - name: "EEmOverETrue"
        linecolor: 1
      - name: "ELcwOverETrue"
        linecolor: 2
    type: "overlay"
    xaxis_title: "E/Etrue"
    yaxis_title: "Number of clusters"
