# Job block defines the output directory and the input file and common plot styles
Job:
  job_name: "Wmunu_13TeV_custom_daod"
  output_directory: "/home/bmondal/Storage/HEP/Work/Project-W-Z/Plotter/plotter/run/Wplusmunu_custom_daod/Plots/"
  file_paths: 
    - "/home/bmondal/Storage/HEP/Work/Project-W-Z/Plotter/plotter/run/Wplusmunu_custom_daod/Root-files/output.root"
  # add text block in the plot for example : sqrt(s) = 13 TeV
  atlas_label:
    name: "Internal" #0.22, 0.9
    position: [ 0.20, 0.89 ]

  plot_label:
    - text: "W^{+}#rightarrow #mu^{+}#nu"
      x: 0.22
      y: 0.85
    - text: ", #sqrt{s} = 13 TeV"
      x: 0.36
      y: 0.85

  # Define common styles
  CommonStyles: &CommonStyles
    markerstyle: 0
    linestyle: 1
    linewidth: 2

# Sample block holds information of individual histograms
Sample:
  - name: "uT_cut3"  # name of the sample
    variable: "WplusmunuSelection_Tight/uT_cut3"  # this is the name of the histogram in the ROOT file
  - name: "nmu_cut3"
    variable: "WplusmunuSelection_Tight/nmu_cut3"
  - name: "muEta_cut3"
    variable: "WplusmunuSelection_Tight/muEta_cut3"
  - name: "muPt_cut3"
    variable: "WplusmunuSelection_Tight/muPt_cut3"
  - name: "met_cut3"
    variable: "WplusmunuSelection_Tight/met_cut3"
  - name: "mT_cut3"
    variable: "WplusmunuSelection_Tight/mT_cut3"
  - name: "ptcone20topT_cut3"
    variable: "WplusmunuSelection_Tight/ptcone20topT_cut3"
  - name: "uParLepton_cut3"
    variable: "WplusmunuSelection_Tight/uParLepton_cut3"
  - name: "uParLepton_cut4"
    variable: "WplusmunuSelection_Tight/uParLepton_cut4"
  - name: "uParLepton_vs_ptcone20_cut3"
    variable: "WplusmunuSelection_Tight/uParLepton_vs_ptcone20_cut3"
  - name: "WpT_Reco_vs_ptcone20topT_cut3"
    variable: "WplusmunuSelection_Tight/WpT_Reco_vs_ptcone20topT_cut3"
  - name: "muPhi_vs_ptcone20topT_cut3"
    variable: "WplusmunuSelection_Tight/muPhi_vs_ptcone20topT_cut3"
  - name: "muEta_vs_ptcone20topT_cut3"
    variable: "WplusmunuSelection_Tight/muEta_vs_ptcone20topT_cut3"
  - name: "muEtaSF_vs_ptcone20topT_cut3"
    variable: "WplusmunuSelection_Tight/muEtaSF_vs_ptcone20topT_cut3"
  - name: "muPt_vs_ptcone20topT_cut3"
    variable: "WplusmunuSelection_Tight/muPt_vs_ptcone20topT_cut3"
  - name: "uT_vs_ptcone20topT_cut3"
    variable: "WplusmunuSelection_Tight/uT_vs_ptcone20topT_cut3"
  - name: "met_vs_ptcone20topT_cut3"
    variable: "WplusmunuSelection_Tight/met_vs_ptcone20topT_cut3"
  - name: "mT_vs_ptcone20topT_cut3"
    variable: "WplusmunuSelection_Tight/mT_vs_ptcone20topT_cut3"
  - name: "SET_vs_ptcone20topT_cut3"
    variable: "WplusmunuSelection_Tight/SET_vs_ptcone20topT_cut3"
  - name: "SETUE_vs_ptcone20topT_cut3"
    variable: "WplusmunuSelection_Tight/SETUE_vs_ptcone20topT_cut3"
  - name: "recoil_PAR_lep_vs_ptcone20topT_cut3"
    variable: "WplusmunuSelection_Tight/recoil_PAR_lep_vs_ptcone20topT_cut3"
  - name: "recoil_PERP_lep_vs_ptcone20topT_cut3"
    variable: "WplusmunuSelection_Tight/recoil_PERP_lep_vs_ptcone20topT_cut3"
  - name: "mT_ut1_vs_ptcone20topT_cut3"
    variable: "WplusmunuSelection_Tight/mT_ut1_vs_ptcone20topT_cut3"
  - name: "mT_ut2_vs_ptcone20topT_cut3"
    variable: "WplusmunuSelection_Tight/mT_ut2_vs_ptcone20topT_cut3"
  - name: "mT_ut3_vs_ptcone20topT_cut3"
    variable: "WplusmunuSelection_Tight/mT_ut3_vs_ptcone20topT_cut3"
  - name: "mT_ut4_vs_ptcone20topT_cut3"
    variable: "WplusmunuSelection_Tight/mT_ut4_vs_ptcone20topT_cut3"
  - name: "mT_ut5_vs_ptcone20topT_cut3"
    variable: "WplusmunuSelection_Tight/mT_ut5_vs_ptcone20topT_cut3"
  - name: "muPt_ut1_vs_ptcone20topT_cut3"
    variable: "WplusmunuSelection_Tight/muPt_ut1_vs_ptcone20topT_cut3"
  - name: "muPt_ut2_vs_ptcone20topT_cut3"
    variable: "WplusmunuSelection_Tight/muPt_ut2_vs_ptcone20topT_cut3"
  - name: "muPt_ut3_vs_ptcone20topT_cut3"
    variable: "WplusmunuSelection_Tight/muPt_ut3_vs_ptcone20topT_cut3"
  - name: "muPt_ut4_vs_ptcone20topT_cut3"
    variable: "WplusmunuSelection_Tight/muPt_ut4_vs_ptcone20topT_cut3"
  - name: "muPt_ut5_vs_ptcone20topT_cut3"
    variable: "WplusmunuSelection_Tight/muPt_ut5_vs_ptcone20topT_cut3"
  - name: "met_ut1_vs_ptcone20topT_cut3"
    variable: "WplusmunuSelection_Tight/met_ut1_vs_ptcone20topT_cut3"
  - name: "met_ut2_vs_ptcone20topT_cut3"
    variable: "WplusmunuSelection_Tight/met_ut2_vs_ptcone20topT_cut3"
  - name: "met_ut3_vs_ptcone20topT_cut3"
    variable: "WplusmunuSelection_Tight/met_ut3_vs_ptcone20topT_cut3"
  - name: "met_ut4_vs_ptcone20topT_cut3"
    variable: "WplusmunuSelection_Tight/met_ut4_vs_ptcone20topT_cut3"
  - name: "met_ut5_vs_ptcone20topT_cut3"
    variable: "WplusmunuSelection_Tight/met_ut5_vs_ptcone20topT_cut3"


# Every block in the Plot block holds a plot
Plot:
  - name: "uT"  # this is the name of the plot
    samples: [{name: "uT_cut3",linecolor: 1}]
    type: "overlay"  # different typs of plots: overlay, simple_th2, stack ...
    y_label: "Events"  # y-axis label
    x_range: [0, 150]  # x-axis range

  - name: "nmu"
    samples: [{name: "nmu_cut3", linecolor: 1}]
    type: "overlay"
    y_label: "Events"
    x_range: [0, 5]

  - name: "muEta"
    samples:
      - name: "muEta_cut3"
        linecolor: 1
    type: "overlay"
    y_label: "Events"
    x_range: [-3, 3]

  - name: "muPt"
    samples:
      - name: "muPt_cut3"
        linecolor: 1
    type: "overlay"
    y_label: "Events"
    x_range: [0, 150]

  - name: "met"
    samples:
      - name: "met_cut3"
        linecolor: 1
    type: "overlay"
    y_label: "Events"
    x_range: [0, 150]

  - name: "mT"
    samples:
      - name: "mT_cut3"
        linecolor: 1
    type: "overlay"
    y_label: "Events"
    x_range: [0, 150]

  - name: "ptcone20topT"
    samples:
      - name: "ptcone20topT_cut3"
        linecolor: 1
    type: "overlay"

  - name: "uParLepton"
    samples:
      - name: "uParLepton_cut3"
        linecolor: 1
      - name: "uParLepton_cut4"
        linecolor: 2
    type: "overlay"
    y_label: "Events"
    x_range: [-20,20]

  - name: "uParLepton_vs_ptcone20"
    samples:
      - name: "uParLepton_vs_ptcone20_cut3"
    type: "simple_th2"

  - name: "WpT_Reco_vs_ptcone20topT"
    samples:
      - name: "WpT_Reco_vs_ptcone20topT_cut3"
    type: "simple_th2"

  - name: "muPhi_vs_ptcone20topT"
    samples:
      - name: "muPhi_vs_ptcone20topT_cut3"
    type: "simple_th2"

  - name: "muEta_vs_ptcone20topT"
    samples:
      - name: "muEta_vs_ptcone20topT_cut3"
    type: "simple_th2"

  - name: "muEtaSF_vs_ptcone20topT"
    samples:
      - name: "muEtaSF_vs_ptcone20topT_cut3"
    type: "simple_th2"

  - name: "muPt_vs_ptcone20topT"
    samples:
      - name: "muPt_vs_ptcone20topT_cut3"
    type: "simple_th2"

  - name: "uT_vs_ptcone20topT"
    samples:
      - name: "uT_vs_ptcone20topT_cut3"
    type: "simple_th2"

  - name: "met_vs_ptcone20topT"
    samples:
      - name: "met_vs_ptcone20topT_cut3"
    type: "simple_th2"

  - name: "mT_vs_ptcone20topT"
    samples:
      - name: "mT_vs_ptcone20topT_cut3"
    type: "simple_th2"

  - name: "SET_vs_ptcone20topT"
    samples:
      - name: "SET_vs_ptcone20topT_cut3"
    type: "simple_th2"

  - name: "SETUE_vs_ptcone20topT"
    samples:
      - name: "SETUE_vs_ptcone20topT_cut3"
    type: "simple_th2"

  - name: "recoil_PAR_lep_vs_ptcone20topT"
    samples:
      - name: "recoil_PAR_lep_vs_ptcone20topT_cut3"
    type: "simple_th2"
    y_label: "p_{T}^{cone20}/p_{T}"

  - name: "recoil_PERP_lep_vs_ptcone20topT"
    samples:
      - name: "recoil_PERP_lep_vs_ptcone20topT_cut3"
    type: "simple_th2"
    y_label: "p_{T}^{cone20}/p_{T}"

  - name: "mT_ut1_vs_ptcone20topT"
    samples:
      - name: "mT_ut1_vs_ptcone20topT_cut3"
    type: "simple_th2"

  - name: "mT_ut2_vs_ptcone20topT"
    samples:
      - name: "mT_ut2_vs_ptcone20topT_cut3"
    type: "simple_th2"

  - name: "mT_ut3_vs_ptcone20topT"
    samples:
      - name: "mT_ut3_vs_ptcone20topT_cut3"
    type: "simple_th2"

  - name: "mT_ut4_vs_ptcone20topT"
    samples:
      - name: "mT_ut4_vs_ptcone20topT_cut3"
    type: "simple_th2"

  - name: "mT_ut5_vs_ptcone20topT"
    samples:
      - name: "mT_ut5_vs_ptcone20topT_cut3"
    type: "simple_th2"

  - name: "muPt_ut1_vs_ptcone20topT"
    samples:
      - name: "muPt_ut1_vs_ptcone20topT_cut3"
    type: "simple_th2"

  - name: "muPt_ut2_vs_ptcone20topT"
    samples:
      - name: "muPt_ut2_vs_ptcone20topT_cut3"
    type: "simple_th2"

  - name: "muPt_ut3_vs_ptcone20topT"
    samples:
      - name: "muPt_ut3_vs_ptcone20topT_cut3"
    type: "simple_th2"

  - name: "muPt_ut4_vs_ptcone20topT"
    samples:
      - name: "muPt_ut4_vs_ptcone20topT_cut3"
    type: "simple_th2"

  - name: "muPt_ut5_vs_ptcone20topT"
    samples:
      - name: "muPt_ut5_vs_ptcone20topT_cut3"
    type: "simple_th2"

  - name: "met_ut1_vs_ptcone20topT"
    samples:
      - name: "met_ut1_vs_ptcone20topT_cut3"
    type: "simple_th2"

  - name: "met_ut2_vs_ptcone20topT"
    samples:
      - name: "met_ut2_vs_ptcone20topT_cut3"
    type: "simple_th2"

  - name: "met_ut3_vs_ptcone20topT"
    samples:
      - name: "met_ut3_vs_ptcone20topT_cut3"
    type: "simple_th2"

  - name: "met_ut4_vs_ptcone20topT"
    samples:
      - name: "met_ut4_vs_ptcone20topT_cut3"
    type: "simple_th2"

  - name: "met_ut5_vs_ptcone20topT"
    samples:
      - name: "met_ut5_vs_ptcone20topT_cut3"
    type: "simple_th2"
